name: Run start.sh script
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Run start.sh
      run: |
        chmod +x ./start.sh
        sudo apt update
        sudo apt install -y python3
        ./start.sh --cleanup
    - name: Upload floppy.img
      uses: actions/upload-artifact@v4
      with:
       name: floppy.img
       path: ./floppy/floppy.img


  upload-release-asset:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: floppy.img
          path: .
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
        with:
          tag_name: main-${{ github.sha }}
          release_name: Release-main${{ github.sha }}
          draft: false
          prerelease: false
      - name: Upload Release Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./floppy.img
          asset_name: floppy.img
          asset_content_type: application/octet-stream