name: Run start.sh script
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Run start.sh
      run: |
        chmod +x ./start.sh
        sudo apt update
        sudo apt install -y python3
        ./start.sh --cleanup
